### ISSUE TITLE
pb syntaxique "we open data, we make them used and useful"

### ISSUE THREAD

**Issue by joelgombin** [datactivist/datactivist.github.io#9]
(thx @jasmin-sadat)

**Comment by joelgombin** [comment]
@samgoeta on met quoi d'après toi ?

**Comment by SylvainLapoix** [comment]
Le problème est sur le sens de "used" ou sur le zeugma ?

Sinon, on peut dire : 

> "We open data / We make them reused / And useful"
> "We open data / We help to reuse it / To make it useful"

Ou alors, plus concept : 
> "Opening data / Helping to reuse it / Making it useful"

**Comment by samgoeta** [comment]
@SylvainLapoix Le problème est que "make something used", ça ne marche pas en anglais. 

Donc je dirais tout simplement "We open data, we make them useful" 

Qu'en dites vous ?

**Comment by jasmin-sadat** [comment]
Tout à fait d'accord avec @samgoeta ! Je mettrai même plus court: We open data and make them useful.

**Comment by samgoeta** [comment]
C'est fait, merci ! https://github.com/datactivist/datactivist.github.io/commit/10e0543c281702824cb52d183ab55e3f474fe442
